title: TextDeformer Geometry Manipulation using Text Guidance
description: William Gao*<sup>1</sup>, Noam Aigerman<sup>2</sup>, Thibault Groueix<sup>2</sup>, Vladimir G. Kim<sup>2</sup>, Rana Hanocka<sup>1</sup>
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
colors:
    gradient_left: "#155799"
    gradient_right: "#36008d"

paper:
  affiliations: <sup>1</sup>University Of Chicago, &nbsp; <sup>2</sup>Adobe Research
